#!/usr/bin/env bash

# Add bash-utils, needs to use this complex syntax in order to work from any working directory
source "$(dirname "$(realpath "$0")")/../scripts/bash-utils.sh"

echo "Running pre-commit git hook..."

# TODO implement!
#"$SCRIPTS_DIR"/pre-commit.sh

echo "WARNING: not yet implemented"
#echo "pre-commit git hook finished successfully"
