#!/usr/bin/env bash

# Add bash-utils, needs to use this complex syntax in order to work from any working directory
source "$(dirname "$(realpath "$0")")/../scripts/bash-utils.sh"

echo "Running pre-push git hook..."

# TODO implement!
#"$SCRIPTS_DIR"/pre-push.sh

echo "WARNING: not yet implemented"
#echo "pre-push git hook finished successfully"
