[project]
name = "pican"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bassam Helal", email = "basshelal@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "clang-format>=23.1.1",
    "clang-tidy>=22.1.8",
    "semgrep>=1.177.0",
]

[project.scripts]
pican = "pican:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
