file(GLOB_RECURSE STACKTRACE_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
file(GLOB_RECURSE STACKTRACE_MODULES "${CMAKE_CURRENT_SOURCE_DIR}/*.cppm")

add_library(STACKTRACE_LIB STATIC ${STACKTRACE_SOURCES})

target_sources(STACKTRACE_LIB
        PUBLIC
        FILE_SET CXX_MODULES
        BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/..
        FILES ${STACKTRACE_MODULES}
)

set_target_properties(STACKTRACE_LIB PROPERTIES
        CXX_STANDARD 23
        CXX_STANDARD_REQUIRED ON
        CXX_EXTENSIONS OFF
)

target_link_libraries(STACKTRACE_LIB PUBLIC ${LIBBACKTRACE_LIB})

target_include_directories(STACKTRACE_LIB PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/.. ${LIBBACKTRACE_INCLUDE_DIR})