file(GLOB_RECURSE STACKTRACE_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")

add_library(STACKTRACE_LIB STATIC ${STACKTRACE_SOURCES})

target_link_libraries(STACKTRACE_LIB PUBLIC ${LIBBACKTRACE_LIB})

target_include_directories(STACKTRACE_LIB PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/.. ${LIBBACKTRACE_INCLUDE_DIR})